#pragma once

#include "Core/Base.h"

#include <QWidget>
#include "Renderer/CameraSettings.h"

class QVBoxLayout;
class QComboBox;

namespace Ui {
    class CameraControlWidget; // Use the name of your .ui file here (without the suffix)
}

class CameraSettingsWidget : public QWidget
{
	Q_OBJECT
	Q_ENUM(CameraMode)
public:
	CameraSettingsWidget(QWidget* parent = nullptr);
	~CameraSettingsWidget();

signals:
    /**
     * @brief Emitted when the user selects a new camera mode from the dropdown.
     * @param newMode The newly selected CameraMode.
     */
    void OnCameraModeChanged(CameraMode newMode);

private slots:
    // Slot to handle the QComboBox's signal
    void OnComboBoxIndexChanged(int index);
private:
    // UI elements
    Ui::CameraControlWidget* ui;

    CameraMode m_CurrentCameraMode = CameraMode::ROAM;

    // Optional: Pointer to the UI generated by Qt Designer
	RoamCameraSettings m_RoamSettings;
	OrbitCameraSettings m_OrbitSettings;

};